<?php
add_action('wp_footer', 'qstb_show_box', 20);
add_action("wp_enqueue_scripts","qstb_load_assets");

/*Load the neccessary stylesheets and scripts!*/
function qstb_load_assets() {
	$options = qstb_get_options();
	wp_enqueue_style('qoate-scroll-triggered-box', QSTB_PLUGIN_URL . '/assets/css/styles.php?vpos='.$options['vplacement'].'&hpos='.$options['hplacement']);

	$sac = 0;
	if((is_single() || is_page()) && (comments_open() && $options['show_at_comments'] == '1')) { $sac = '1'; }
	if((is_single() || is_page()) && $options['show_at_comments'] == '2') { $sac = '2'; }

	wp_enqueue_script('jquery');
	wp_enqueue_script('qoate-scroll-triggered-box', QSTB_PLUGIN_URL .'/assets/js/script.php?anim='.$options['animation'].'&vpos='.$options['vplacement'].'&perc='.$options['percentage'].'&sac='.$sac);
}


function qstb_show_box(){
	$post = get_post();
	$options = qstb_get_options();
	$sb_options = get_option('qoate_sb_settings',array('text'=>'Liked this page? Share it!'));

	$content = '<div id="qoate-scroll-triggered-box">';

	if($options['with_minimize']=='1') {
		$content .= '<img style="position:absolute; cursor:pointer; right:0; margin:2px; " id="qoate_close_box" src="' . QSTB_PLUGIN_URL . '/assets/img/close.png" alt="Close" />';
		$content .= '<img style="position:absolute; display:none; cursor:pointer; right:0;" id="qoate_show_box" src="' . QSTB_PLUGIN_URL . '/assets/img/show_' . $options['vplacement'] . '.png" alt="Show" />';
	}

	if($sb_options['use_bookmarks'] != '1') {
		$content .= '<div class="qoate_box_content">';
		$content .= $options['text'];
	} else {
		$content.= '<h4>'.$sb_options['text'].'</h4>';
		$content .= '<div class="qoate_box_content">';
		
		// Load the post's and blog's data
		$blogname 	= urlencode(get_bloginfo('name')." ".get_bloginfo('description'));
		$blogrss	= get_bloginfo('rss2_url'); 
		if(is_home() || is_archive()) {
			$excerpt = urlencode(substr(get_bloginfo('description'), 0, 250));
			$excerpt = str_replace('+', '%20', $excerpt);
			$permalink = get_bloginfo('wpurl');
			$title = 'Check out this great website!';
		} else {
			// Grab the excerpt, if there is no excerpt, create one
			$excerpt	= urlencode(strip_tags(strip_shortcodes($post->post_excerpt)));

			if ($excerpt == "") {
				$excerpt = urlencode(substr(strip_tags(strip_shortcodes($post->post_content)), 0, 250));
			}
			// Clean the excerpt for use with links
			$excerpt	= str_replace('+','%20',$excerpt);
			$permalink 	= urlencode(get_permalink($post->ID));
			$title 		= str_replace('+','%20',urlencode($post->post_title));
		}

		$social_sites = qstb_get_social_mediums();
		foreach($social_sites as $name => $site) {
			if($sb_options[$name]=='1') {
			$url = $site['url'];
			$url = str_replace('TITLE', $title, $url);
			$url = str_replace('RSS', $rss, $url);
			$url = str_replace('PERMALINK',$permalink,$url);
			$url = str_replace('BLOGNAME', $blogname, $url);
			$url = str_replace('EXCERPT', $excerpt, $url);
			$url = str_replace('FEEDLINK', $blogrss, $url);
			
			$content.= '<a rel="nofollow" target="_blank" href="' . esc_attr($url) . '">';
			$content.= '<img src="' . QSTB_PLUGIN_URL .'/assets/img/social-media-icons/' . strtolower($name) . '.png" alt='. esc_attr($name) .' />';
			$content.='</a>';
			}
		}
	}
	$content .='</div>';
	$content .= '<!-- This Box is generated by Qoate Scroll Triggered Box! -->';
	$content .= '</div>';

	echo $content;
}




?>